---

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

    reviewers:
      - "charlesrocket"

    commit-message:
      prefix: "ops"
      include: "scope"
