---

name: CD
"on":
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string

env:
  ZIG_VERSION: 0.13.0

concurrency:
  group: "pages"
  cancel-in-progress: true


permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  release:
    name: Create release
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy documentation
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: Generate documentation
        run: zig build docs

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: zig-out/doc/

      - name: Deploy documentation
        uses: actions/deploy-pages@v4
