---

name: CD
"on":
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string

permissions:
  contents: read

jobs:
  release:
    name: Create release
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
