---
name: CD
"on":
  push:
    tags:
      - "*"

env:
  ZIG_VERSION: 0.16.0

concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy documentation
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: Generate documentation
        run: zig build docs

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v5
        with:
          path: zig-out/doc/

      - name: Deploy documentation
        uses: actions/deploy-pages@v5
