---
name: CI
"on": [push, pull_request]

permissions:
  contents: read

env:
  ZIG_VERSION: 0.16.0

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu, macos]
        mode: ["fast", "safe", "small", "off"]

    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v6
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: Build
        run: zig build --release=${{ matrix.mode }} --verbose --summary all
      - name: Test
        run: zig build test --release=${{ matrix.mode }} --summary all

  coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    container:
      image: kcov/kcov
      options: --cap-add=SYS_PTRACE --security-opt seccomp=unconfined

    if: "!startsWith(github.ref, 'refs/tags/')"
    steps:
      - run: |
          apt-get update
          apt-get install -y curl gpg git tar xz-utils

      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}
          use-cache: false

      - uses: actions/checkout@v6
      - run: git config --global --add safe.directory /__w/ghext/ghext
      - name: Generate coverage
        run: zig build coverage --summary all

      - name: Upload coverage
        uses: codecov/codecov-action@v6
        with:
          directory: kcov-out
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    name: Format
    runs-on: ubuntu-latest
    if: "!startsWith(github.ref, 'refs/tags/')"
    steps:
      - uses: actions/checkout@v6
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}

      - run: zig fmt --check .

  release:
    needs: [test]
    permissions:
      contents: write
      pages: write
      id-token: write

    if: |
      github.repository_owner == 'charlesrocket' &&
      startsWith(github.ref, 'refs/tags/')

    uses: ./.github/workflows/cd.yml
    with:
      tag_name: ${{ github.ref_name }}
